import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import { connectWithRetry } from "@/lib/mongodb";
import { Toaster } from "@/components/ui/toaster";
import LoadingProvider from "./LoadingProvider";

const yekanBakhLight = localFont({
  src: "./fonts/YekanBakhFaNum-Light.woff2",
  variable: "--font-yekanBakh-light",
  weight: "100 200",
});
const yekanBakhRegular = localFont({
  src: "./fonts/YekanBakhFaNum-Regular.woff2",
  variable: "--font-yekanBakh-regular",
  weight: "300 500",
});

const yekanBakhBold = localFont({
  src: "./fonts/YekanBakhFaNum-Bold.woff2",
  variable: "--font-yekanBakh-bold",
  weight: "600 700",
});
const yekanBakhBlack = localFont({
  src: "./fonts/YekanBakhFaNum-Black.woff2",
  variable: "--font-yekanBakh-black",
  weight: "800",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  connectWithRetry();

  return (
    <html lang="fa" dir="rtl">
      <Providers>
        <body
          className={`${yekanBakhLight.variable} ${yekanBakhRegular.variable} ${yekanBakhBold.variable} ${yekanBakhBlack.variable} antialiased`}
        >
          <LoadingProvider>
            {children}
            <Toaster />
          </LoadingProvider>
        </body>
      </Providers>
    </html>
  );
}
